---
label: produits
hide_body: false
is_partial: false
fields:
- type: text
  name: name
  label: nom du produit
- type: textarea
  name: mini_desc
  label: mini description
- type: select
  name: type
  config:
    source:
      type: simple
    options:
    - Berline
    - 4x4
    - Taxi
  label: type
- type: file
  name: image_principale
  label: image principale
- type: image_gallery
  name: images
  label: images
pages:
- _produits/soren.md
